library product.entity.dart;

import 'package:auctionvillage/core/domain/entities/entities.dart';
import 'package:auctionvillage/features/dashboard/domain/index.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kt_dart/collection.dart';

part 'product.entity.freezed.dart';

@freezed
@immutable
class Product extends BaseEntity with _$Product {
  const Product._();

  const factory Product({
    required UniqueId<String?> id,
    required DealCategory category,
    required BasicTextField<String?> name,
    @Default(KtList.empty()) KtList<MediaField> photos,
    @Default(false) bool isActive,
    @Default(DealStatus.pending) DealStatus dealStatus,
    required BasicTextField<String?> lga,
    required BasicTextField<String?> state,
    User? vendor,
    Deal? deal,
    BrandInformation? brandInformation,
    ShippingInformation? shippingInformation,
    TermsInformation? termsInformation,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) = _Product;

  factory Product.blank({
    String? id,
    DealCategory? category,
    String? name,
    String? lga,
    String? state,
    bool? active,
    DealStatus? dealStatus,
    List<String> photos = const [],
    User? vendor,
    Deal? deal,
    BrandInformation? brand,
    ShippingInformation? shipping,
    TermsInformation? terms,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) =>
      Product(
        id: UniqueId.fromExternal(id),
        category: category ?? DealCategory.blank(),
        deal: deal,
        isActive: active ?? false,
        dealStatus: dealStatus ?? DealStatus.pending,
        vendor: vendor,
        photos: photos.map((e) => MediaField(e)).toImmutableList(),
        name: BasicTextField(name),
        lga: BasicTextField(lga),
        state: BasicTextField(state),
        brandInformation: brand,
        shippingInformation: shipping,
        termsInformation: terms,
        createdAt: createdAt,
        updatedAt: updatedAt,
      );

  // factory Product.blank() => Product(
  //       id: UniqueId.fromExternal(null),
  //       itemCategory: BasicTextField(null),
  //       itemSubCategory: BasicTextField(null),
  //       itemDescription: BasicTextField(null),
  //       state: BasicTextField(null),
  //       town: BasicTextField(null),
  //       brand: BasicTextField(null),
  //       model: BasicTextField(null),
  //       yearOfManufacture: DateTimeField(null),
  //       color: BasicTextField(null),
  //       itemPrice: AmountField(0),
  //       basePrice: AmountField(0),
  //       quantity: BasicTextField(0),
  //       startDate: DateTimeField(null),
  //       endDate: DateTimeField(null),
  //       startTime: DateTimeField(null),
  //       endTime: DateTimeField(null),
  //       weight: BasicTextField(null),
  //       length: BasicTextField(null),
  //       width: BasicTextField(null),
  //       height: BasicTextField(null),
  //       shippingDescription: BasicTextField(null),
  //       yearOfPurchase: DateTimeField(null),
  //       otherInformation: BasicTextField(null),
  //     );

  // static List<Product> get dummy => [
  //       Product(
  //         id: UniqueId.v4(),
  //         itemCategory: BasicTextField('Electronics'),
  //         itemSubCategory: BasicTextField('Mobile'),
  //         itemDescription: BasicTextField('Samsung Galaxy S10'),
  //         state: BasicTextField('Karnataka'),
  //         town: BasicTextField('Bangalore'),
  //         brand: BasicTextField('Samsung'),
  //         model: BasicTextField('S10'),
  //         yearOfManufacture: DateTimeField(DateTime.now()),
  //         color: BasicTextField('Black'),
  //         itemPrice: AmountField(10000),
  //         basePrice: AmountField(10000),
  //         quantity: BasicTextField(1),
  //         startDate: DateTimeField(DateTime.now()),
  //         endDate: DateTimeField(DateTime.now()),
  //         startTime: DateTimeField(DateTime.now()),
  //         endTime: DateTimeField(DateTime.now()),
  //         weight: BasicTextField(4.8),
  //         length: BasicTextField(60.8),
  //         width: BasicTextField(30.8),
  //         height: BasicTextField(60.8),
  //         shippingDescription: BasicTextField('Delivered in 2 days'),
  //         yearOfPurchase: DateTimeField(DateTime.now()),
  //         otherInformation: BasicTextField('No other information'),
  //         biddingType: BiddingType.online,
  //         condition: ItemCondition.good,
  //         deliveryPeriod: DeliveryPeriod.later,
  //         isPickup: false,
  //       ),
  //       Product(
  //         id: UniqueId.v4(),
  //         itemCategory: BasicTextField('Electronics'),
  //         itemSubCategory: BasicTextField('Automobile'),
  //         itemDescription: BasicTextField('Audi A8'),
  //         state: BasicTextField('Karnataka'),
  //         town: BasicTextField('Bangalore'),
  //         brand: BasicTextField('Audi'),
  //         model: BasicTextField('A8'),
  //         yearOfManufacture: DateTimeField(DateTime.now()),
  //         color: BasicTextField('Green'),
  //         itemPrice: AmountField(27300000),
  //         basePrice: AmountField(27300000),
  //         quantity: BasicTextField(8),
  //         startDate: DateTimeField(DateTime.now()),
  //         endDate: DateTimeField(DateTime.now()),
  //         startTime: DateTimeField(DateTime.now()),
  //         endTime: DateTimeField(DateTime.now()),
  //         weight: BasicTextField(4.8),
  //         length: BasicTextField(60.8),
  //         width: BasicTextField(30.8),
  //         height: BasicTextField(60.8),
  //         shippingDescription: BasicTextField('Delivered in 19 days'),
  //         yearOfPurchase: DateTimeField(DateTime.now()),
  //         otherInformation: BasicTextField('No other information'),
  //         condition: ItemCondition.poor,
  //       ),
  //       Product(
  //         id: UniqueId.v4(),
  //         itemCategory: BasicTextField('Electronics'),
  //         itemSubCategory: BasicTextField('Mobile'),
  //         itemDescription: BasicTextField('Samsung Galaxy S10'),
  //         state: BasicTextField('Karnataka'),
  //         town: BasicTextField('Bangalore'),
  //         brand: BasicTextField('Samsung'),
  //         model: BasicTextField('S10'),
  //         yearOfManufacture: DateTimeField(DateTime.now()),
  //         color: BasicTextField('Black'),
  //         itemPrice: AmountField(10000),
  //         basePrice: AmountField(10000),
  //         quantity: BasicTextField(1),
  //         startDate: DateTimeField(DateTime.now()),
  //         endDate: DateTimeField(DateTime.now()),
  //         startTime: DateTimeField(DateTime.now()),
  //         endTime: DateTimeField(DateTime.now()),
  //         weight: BasicTextField(4.8),
  //         length: BasicTextField(60.8),
  //         width: BasicTextField(30.8),
  //         height: BasicTextField(60.8),
  //         shippingDescription: BasicTextField('Delivered in 2 days'),
  //         yearOfPurchase: DateTimeField(DateTime.now()),
  //         otherInformation: BasicTextField('No other information'),
  //         biddingType: BiddingType.online,
  //         condition: ItemCondition.good,
  //         deliveryPeriod: DeliveryPeriod.later,
  //         isPickup: false,
  //       ),
  //       Product(
  //         id: UniqueId.v4(),
  //         itemCategory: BasicTextField('Electronics'),
  //         itemSubCategory: BasicTextField('Automobile'),
  //         itemDescription: BasicTextField('Audi A8'),
  //         state: BasicTextField('Karnataka'),
  //         town: BasicTextField('Bangalore'),
  //         brand: BasicTextField('Audi'),
  //         model: BasicTextField('A8'),
  //         yearOfManufacture: DateTimeField(DateTime.now()),
  //         color: BasicTextField('Green'),
  //         itemPrice: AmountField(27300000),
  //         basePrice: AmountField(27300000),
  //         quantity: BasicTextField(8),
  //         startDate: DateTimeField(DateTime.now()),
  //         endDate: DateTimeField(DateTime.now()),
  //         startTime: DateTimeField(DateTime.now()),
  //         endTime: DateTimeField(DateTime.now()),
  //         weight: BasicTextField(4.8),
  //         length: BasicTextField(60.8),
  //         width: BasicTextField(30.8),
  //         height: BasicTextField(60.8),
  //         shippingDescription: BasicTextField('Delivered in 19 days'),
  //         yearOfPurchase: DateTimeField(DateTime.now()),
  //         otherInformation: BasicTextField('No other information'),
  //         condition: ItemCondition.poor,
  //       ),
  //       Product(
  //         id: UniqueId.v4(),
  //         itemCategory: BasicTextField('Electronics'),
  //         itemSubCategory: BasicTextField('Mobile'),
  //         itemDescription: BasicTextField('Samsung Galaxy S10'),
  //         state: BasicTextField('Karnataka'),
  //         town: BasicTextField('Bangalore'),
  //         brand: BasicTextField('Samsung'),
  //         model: BasicTextField('S10'),
  //         yearOfManufacture: DateTimeField(DateTime.now()),
  //         color: BasicTextField('Black'),
  //         itemPrice: AmountField(10000),
  //         basePrice: AmountField(10000),
  //         quantity: BasicTextField(1),
  //         startDate: DateTimeField(DateTime.now()),
  //         endDate: DateTimeField(DateTime.now()),
  //         startTime: DateTimeField(DateTime.now()),
  //         endTime: DateTimeField(DateTime.now()),
  //         weight: BasicTextField(4.8),
  //         length: BasicTextField(60.8),
  //         width: BasicTextField(30.8),
  //         height: BasicTextField(60.8),
  //         shippingDescription: BasicTextField('Delivered in 2 days'),
  //         yearOfPurchase: DateTimeField(DateTime.now()),
  //         otherInformation: BasicTextField('No other information'),
  //         biddingType: BiddingType.online,
  //         condition: ItemCondition.good,
  //         deliveryPeriod: DeliveryPeriod.later,
  //         isPickup: false,
  //       ),
  //       Product(
  //         id: UniqueId.v4(),
  //         itemCategory: BasicTextField('Electronics'),
  //         itemSubCategory: BasicTextField('Automobile'),
  //         itemDescription: BasicTextField('Audi A8'),
  //         state: BasicTextField('Karnataka'),
  //         town: BasicTextField('Bangalore'),
  //         brand: BasicTextField('Audi'),
  //         model: BasicTextField('A8'),
  //         yearOfManufacture: DateTimeField(DateTime.now()),
  //         color: BasicTextField('Green'),
  //         itemPrice: AmountField(27300000),
  //         basePrice: AmountField(27300000),
  //         quantity: BasicTextField(8),
  //         startDate: DateTimeField(DateTime.now()),
  //         endDate: DateTimeField(DateTime.now()),
  //         startTime: DateTimeField(DateTime.now()),
  //         endTime: DateTimeField(DateTime.now()),
  //         weight: BasicTextField(4.8),
  //         length: BasicTextField(60.8),
  //         width: BasicTextField(30.8),
  //         height: BasicTextField(60.8),
  //         shippingDescription: BasicTextField('Delivered in 19 days'),
  //         yearOfPurchase: DateTimeField(DateTime.now()),
  //         otherInformation: BasicTextField('No other information'),
  //         condition: ItemCondition.poor,
  //       ),
  //     ];
}
