name: auctionvillage
description: An application for auctions

publish_to: "none"

version: 1.0.4+23

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.28

  auto_route: ^4.2.1

  auto_size_text: ^3.0.0

  awesome_notifications: ^0.6.21

  badges: ^2.0.2

  bloc_concurrency: ^0.2.0

  built_collection: ^5.1.1

  built_value: ^8.4.0

  cached_network_image: ^3.2.0

  carousel_slider: ^4.0.0

  cloudinary_public: ^0.11.0

  connectivity_plus: ^2.3.6

  cupertino_icons: ^1.0.4

  cupertino_list_tile: ^0.2.1

  dartz: ^0.10.1

  date_format: ^2.0.5

  dio: ^4.0.4

  dio_cache_interceptor: ^3.3.0

  dismissible_page: ^0.7.3

  enough_platform_widgets: ^0.4.0

  expandable: ^5.0.1

  extended_nested_scroll_view: ^5.0.0

  firebase_analytics: ^9.2.0

  firebase_core: ^1.19.2

  firebase_crashlytics: ^2.8.5

  firebase_messaging: ^12.0.0

  flutter_bloc: ^8.0.1

  flutter_colorpicker: ^1.0.3

  flutter_datetime_picker: ^1.5.1

  flutter_downloader: ^1.8.1

  flutter_masked_text2:
    git:
      url: https://github.com/Flutter-Fox/flutter_masked_text.git
      ref: hotfix-0.9.1

  flutter_multi_formatter: ^2.5.8

  flutter_native_splash: ^2.2.5

  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: patch/1.0.5+2

  flutter_rating_bar: ^4.0.0

  flutter_screenutil: ^5.4.0

  flutter_spinkit: ^5.1.0

  flutter_svg: ^1.1.1+1

  fluttertoast: ^8.0.8

  flutterwave_standard:
    git:
      url: https://github.com/definitelyme/flutter_standard.git
      ref: fix-exception

  freezed_annotation: ^2.1.0

  get_it: ^7.2.0

  google_fonts: ^3.0.0

  google_sign_in: ^5.4.0

  hive_flutter:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_flutter/

  image_picker: ^0.8.4+10

  in_app_update: ^3.0.0

  inflection3: ^0.5.3+2

  injectable: ^1.5.3

  internet_connection_checker: ^0.0.1+3

  intl: ^0.17.0

  intl_phone_number_input: ^0.7.0+2

  json_annotation: ^4.6.0

  kt_dart: ^0.10.0

  modal_bottom_sheet: ^2.0.0

  new_version: ^0.3.1

  path_provider: ^2.0.8

  permission_handler: ^10.0.0

  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view.git
      ref: 8156907eecfa812b181a5a729d790f6d399f311b

  pretty_dio_logger: ^1.1.1

  pull_to_refresh: ^2.0.0

  retrofit: ^3.0.1+1

  retry: ^3.1.0

  rxdart: ^0.27.5

  search_page: ^2.0.0+1

  share_plus: ^4.0.4

  shared_preferences: ^2.0.12

  shimmer: ^2.0.0

  showcaseview: ^1.1.7

  # sign_in_with_apple: ^4.0.0

  smooth_page_indicator: ^1.0.0+2

  socket_io_client: ^2.0.0

  stream_channel: ^2.1.0

  string_validator: ^0.3.0

  url_launcher: ^6.1.5

  uuid: ^3.0.6

dependency_overrides:
  analyzer: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^4.2.0

  build_runner: ^2.2.0

  built_value_generator: ^8.4.0

  flutter_launcher_icons: ^0.9.3

  flutter_lints: ^2.0.0

  freezed: ^2.1.0+1

  hive_generator:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_generator/

  injectable_generator: ^1.5.4

  json_serializable: ^6.3.1

  logger: ^1.0.0

  pedantic: ^1.11.1

  retrofit_generator:
    git:
      url: https://github.com/Flutter-Fox/retrofit.dart.git
      ref: ft/app_http_client
      path: generator/

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/dashboard/
    - assets/images/dashboard/card_logos/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/svgs/logo/
    - assets/svgs/dashboard/
    - assets/svgs/onboarding/
    - assets/raw/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: AVIcons
      fonts:
        - asset: assets/fonts/AVIcons.ttf
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/san_francisco/SFNSDisplay-Bold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Heavy.otf
          weight: 700
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-HeavyItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Semibold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Thin.otf
          weight: 100
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/san_francisco/SFNSDisplay-Ultralight.otf
          weight: 200
          style: normal
        - asset: assets/fonts/san_francisco/SF-Pro-Display-UltralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/san_francisco/SFNSText-Bold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/san_francisco/SFNSText-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/san_francisco/SFNSText-Heavy.otf
          weight: 700
          style: normal
        - asset: assets/fonts/san_francisco/SFNSText-HeavyItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/san_francisco/SFNSText-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/san_francisco/SFNSText-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/san_francisco/SFNSText-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/san_francisco/SFNSText-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/san_francisco/SFNSText-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/san_francisco/SFNSText-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/san_francisco/SFNSText-Semibold.otf
          weight: 600
          style: normal
