/// Flutter icons AVIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AVIcons
///      fonts:
///       - asset: fonts/AVIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AVIcons {
  AVIcons._();

  static const _kFontFam = 'AVIcons';
  static const String? _kFontPkg = null;

  static const IconData paystack = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutterwave = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_closed = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_open = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_vertical = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_plus = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_artefact = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_automobile = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_general = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_luxury = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData naira = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_chat = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_home = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_live = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_menu = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_sell = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_clip = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_message = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiling_face = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
